### ISSUE TITLE
column blog_blogpost._content does not exist 

### ISSUE THREAD

**Issue by nguyentiendat12032003** [codingforentrepreneurs/talk-to-django#1]
# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    embedding = VectorField(dimensions= EMBEDDING_LENGTH, blank = True, null=True)
    
   but when i run qs = BlogPost.objects.all() 
   it's show me error column blog_blogpost._content does not exist 
![Screenshot 2024-08-09 193355](https://github.com/user-attachments/assets/7d75e982-4ff2-45e5-bb8c-e6e3153e0af6)

**Comment by codingforentrepreneurs** [comment]
Migrate your database
